name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c
    - run: ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.bp APP_PLATFORM=android-24
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
